from flask import Blueprint

api = Blueprint('api', __name__)

from . import authentication, tournaments, players, matches, errors

# This package is used as a blueprint in the flask application totoro.
# It is implementing resource endpoints for establishing
# an api for the application totoro,
# that clients can call the api for altering data of the application
# The api offers serveral endpoints as followed:
# - matches - Matches generated by the application
# - tournaments - Tournaments and all other resources
#   related to an tournament like, sets and teams
# - players - Players, which are registerd on the app
