"""added winner to match

Revision ID: 6467beb77200
Revises: e497e8808343
Create Date: 2016-08-08 15:55:20.898748

"""

# revision identifiers, used by Alembic.
revision = '6467beb77200'
down_revision = 'e497e8808343'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('winner', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'winner')
    ### end Alembic commands ###
