"""tammo session - added match and sets - disabled in tournament set_count as primary

Revision ID: 7c0b191b8769
Revises: 9565f8612790
Create Date: 2016-07-03 20:39:48.736148

"""

# revision identifiers, used by Alembic.
revision = '7c0b191b8769'
down_revision = '9565f8612790'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tournament', 'set_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tournament', 'set_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
