"""empty message

Revision ID: 8c79cac289a9
Revises: None
Create Date: 2016-07-19 14:34:24.263899

"""

# revision identifiers, used by Alembic.
revision = '8c79cac289a9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('tournament_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'matches', 'tournament', ['tournament_id'], ['id'])
    op.add_column('team', sa.Column('history', sa.String(length=120), nullable=True))
    op.add_column('team', sa.Column('points', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'points')
    op.drop_column('team', 'history')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_column('matches', 'tournament_id')
    ### end Alembic commands ###
