"""tammo session - added match and sets - advanced

Revision ID: 9565f8612790
Revises: ee0129f0eb8b
Create Date: 2016-07-03 16:43:48.248183

"""

# revision identifiers, used by Alembic.
revision = '9565f8612790'
down_revision = 'ee0129f0eb8b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('phase', sa.Integer(), nullable=True))
    op.add_column('tournament', sa.Column('max_phase', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament', 'max_phase')
    op.drop_column('matches', 'phase')
    ### end Alembic commands ###
