"""tammo session - added match and sets

Revision ID: ab2a0eb5415c
Revises: e56442440c60
Create Date: 2016-07-01 16:29:17.180212

"""

# revision identifiers, used by Alembic.
revision = 'ab2a0eb5415c'
down_revision = 'e56442440c60'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_a', sa.Integer(), nullable=False),
    sa.Column('score_b', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_a', sa.Integer(), nullable=True),
    sa.Column('team_b', sa.Integer(), nullable=True),
    sa.Column('over', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['team_a'], ['team.id'], ),
    sa.ForeignKeyConstraint(['team_b'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('sets')
    ### end Alembic commands ###
