"""added bh1 and bh2 to team and changed point to float

Revision ID: d5e6aacf8012
Revises: 44d9f08ad24f
Create Date: 2016-08-02 15:39:47.303737

"""

# revision identifiers, used by Alembic.
revision = 'd5e6aacf8012'
down_revision = '44d9f08ad24f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('buchholz1', sa.Float(), nullable=True))
    op.add_column('team', sa.Column('buchholz2', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'buchholz2')
    op.drop_column('team', 'buchholz1')
    ### end Alembic commands ###
