"""added over flag to tournament

Revision ID: e497e8808343
Revises: b5b9467c5bf6
Create Date: 2016-08-02 16:20:32.975667

"""

# revision identifiers, used by Alembic.
revision = 'e497e8808343'
down_revision = 'b5b9467c5bf6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('over', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament', 'over')
    ### end Alembic commands ###
