"""tammo session 1 - relative Relation

Revision ID: e56442440c60
Revises: 8a3c162ac2eb
Create Date: 2016-07-01 16:09:25.703326

"""

# revision identifiers, used by Alembic.
revision = 'e56442440c60'
down_revision = '8a3c162ac2eb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_team',
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_team')
    ### end Alembic commands ###
