"""tammo session - added match and sets - upgraded

Revision ID: ee0129f0eb8b
Revises: ab2a0eb5415c
Create Date: 2016-07-01 16:34:31.403727

"""

# revision identifiers, used by Alembic.
revision = 'ee0129f0eb8b'
down_revision = 'ab2a0eb5415c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sets', sa.Column('match_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sets', 'matches', ['match_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sets', type_='foreignkey')
    op.drop_column('sets', 'match_id')
    ### end Alembic commands ###
